/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author PC_TEACHER
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    private PanelKhoaUI panelKhoaUI;
    private PanelSinhVienGUI panelSinhVienUI;
    public MainFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tabChucNang = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDanhMuc = new javax.swing.JMenu();
        itemKhoa = new javax.swing.JMenuItem();
        itemMonhoc = new javax.swing.JMenuItem();
        itemSinhVien = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuThongKe = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình quản lý giáo vụ");

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/department.png"))); // NOI18N
        jButton1.setText("Khoa");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/student.png"))); // NOI18N
        jButton2.setText("Sinh viên");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jToolBar1.add(jButton2);

        menuDanhMuc.setText("Quản lý danh mục");

        itemKhoa.setText("Danh mục khoa");
        itemKhoa.addActionListener(this::itemKhoaActionPerformed);
        menuDanhMuc.add(itemKhoa);

        itemMonhoc.setText("Danh mục môn học");
        itemMonhoc.addActionListener(this::itemMonhocActionPerformed);
        menuDanhMuc.add(itemMonhoc);

        itemSinhVien.setText("Sinh viên");
        itemSinhVien.addActionListener(this::itemSinhVienActionPerformed);
        menuDanhMuc.add(itemSinhVien);
        menuDanhMuc.add(jSeparator1);

        jMenuItem3.setText("Đăng ký học phần");
        menuDanhMuc.add(jMenuItem3);

        jMenuBar1.add(menuDanhMuc);

        menuThongKe.setText("Báo cáo - Thống kê");
        jMenuBar1.add(menuThongKe);

        menuHelp.setText("Hướng dẫn sử dụng");
        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKhoaActionPerformed
        // TODO add your handling code here:
        FrmKhoaUI frm = new FrmKhoaUI();
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
    }//GEN-LAST:event_itemKhoaActionPerformed

    private void itemSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSinhVienActionPerformed
        // TODO add your handling code here:
        showFrmSinhVien();
    }//GEN-LAST:event_itemSinhVienActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //showFrmSinhVien();
        if(panelSinhVienUI==null)
        {
           panelSinhVienUI = new PanelSinhVienGUI();
           tabChucNang.add("Quản lý sinh viên", panelSinhVienUI);          
        }
        tabChucNang.setSelectedComponent(panelSinhVienUI);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(panelKhoaUI==null)
        {
           panelKhoaUI = new PanelKhoaUI();
           tabChucNang.add("Quản lý khoa", panelKhoaUI);
        }
        tabChucNang.setSelectedComponent(panelKhoaUI);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemMonhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMonhocActionPerformed
        // TODO add your handling code here:
        showFrmMonHoc();
    }//GEN-LAST:event_itemMonhocActionPerformed

    private void showFrmSinhVien()
    {
        FrmSinhVienUI frm = new FrmSinhVienUI();
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
    }
    
    private void showFrmMonHoc()
    {
        FrmMonHocUI frm = new FrmMonHocUI();
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemKhoa;
    private javax.swing.JMenuItem itemMonhoc;
    private javax.swing.JMenuItem itemSinhVien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuDanhMuc;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuThongKe;
    private javax.swing.JTabbedPane tabChucNang;
    // End of variables declaration//GEN-END:variables
}
